### ISSUE TITLE
plugin installation doesn't work from some locations

### ISSUE THREAD

**Issue by alecgregory** [beezwax/bzBond#16]
If I am in my home directory and run `/var/www/bzbond-server/bin/install-plug.sh` I get an error which seems to be from the git clone command:
```
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/beezwax/bzbond-server-plugin-example.git
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
```

But in other directories it works. For example if I am in `/var/www/bzbond-server/bin` or `/var/www/bzbond-server` and run `/var/www/bzbond-server/bin/install-plug.sh` then the plugin installs fine.

**Comment by gosukiwi** [comment]
So seems like npm will always use the `ssh` protocol, even if you say `npm install https://github.com/some/repo` (trying to force https instead of ssh).

For that protocol you **must** have a public key, even if it's a public repo, so npm will fail if the current user doesn't have a public key in `~/.ssh/id_rsa.pub`. And not only that, that public key must be associated with a GitHub account.

So I ended up with the following approach:

1. We have a `/var/www/bzbond-server/installed-plugins` folder
2. All plugins are installed there, and then using `npm install ./installed-plugins/folder-name`

That way, the installation script can use https for getting a git repo. Also if the script is given a filesystem path, it will copy it into `installed-plugins` (alternatively it could use a symlink but I opted for the simplest option).
